swagger: "2.0"
info:
  title: Knowshare API
  description: This is Knowshare Api documentation
  version: 1.0
  servers:
    - url: "http://localhost:3000/"
      description: This is the local server
    - url: "https://knowshare-backend-alx.vercel.app/"
      description: Knowshare server

schemes: [http, https]

paths:
  /login:
    post:
      sumary: Logs a user into their account
      description: |
            When a user has been succesfully logged in a token is returned
            which shiuld be added to the Authorization Header as Bearer token to authenticate subsequent requests

      parameters:
        - name: Email
          description: User's Email
          in: body
          required: true
          type: string
        - name: Password
          description: User's Password
          in: body
          required: true
          type: string
      responses:
        200:
          description: An Object with a jwt token
        404:
          description: User does not exist
